#cloud-config
users:
  - name: ubuntu # Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL # Sude regln für diesen Benutzer
    groups: users, admin #gruppen in der user drinnen ist
    home: /home/ubuntu # home Path
    shell: /bin/bash  #The default shell for this user
    ssh_authorized_keys: #public SSH key for the user
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4P7TpeDENu65kk/7PRHyIOYYMddZae7YOG++N71zJ8H1NZHQX/uEZlMMTFzvRuR4YXxllqCxJ9FkmJra/rGAYdA4IvVebz/LxZbYmBH0TO0DKC7RPIzU9mZrC1cppt/cGRKIhriFcwshognUKijqmCD4jW0uFpoBRLAkSMDgyIiwCft9zcREqyuV+DLZvyQeuB39U4n6EMQMs2M239ii6D9RW+gUq8HBE7xmQccAhej9sKVcJrEizM3+liFWRlpr0fJG9ubmVWmpgooa5xZxTCL0hcag7KZtHV+CRQhFhSxHv6HAyTqkgzcQ9QNVbF1jBW8IyvHrTPC4mOmVXfXgJ aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCz/wpWmsCxaQyuNFrIachc/q9nUdByoUcBcicl/wnKLFktKp6du9np9Uhmo4M0tVHNnWCt5uNEi2ks/0XEbg2J+4heuAAKEDr/TVbgabiWGclYKpEWZvmw8gsQwfpAKVG4aS2re7wB2uhw82ZqzJVpGm3ne+sNnz5uVrxN8HUnuR2OWJD6bA9l/fBmE6zdObVXgrCJGjZmVyB5GMeTDJKExgoBpLggZn9CNdu7Sx989xtNLehu6SWM+mGCq9Lcu7usiPG+SuEb8XynYaCOnv8+Oko6SYeJ9Omq/E7Eg6vZHqCbBQ81TIZrGKcikLmF2xP7EOprGOSPVewke7ak7vvmOI+p/RfIAyXj1+GYny+esk9G+qDRFXP9uiIlMfH1oGkQkztvSDMH+EOHqgY66NWQJPj83CaWH/euR0MROHXjm1ar3RuN9qcASAnzCOQQ1FMwFkpIV5x0NDRx0Zp1rLt8ZUFykmIuHZI4g9u6RdAiuWUxx9/eF0fXZa6Ju7GEMKeMtZxJJjmB/WCOylbkT+NPw5RcxgyRLKmUAicnYKXBmULY3pQM/Ui8KiCyJqRbLDBAR+XZYsZ7X5uhcuteu8KIfA2xEbInB4Q3c0DnnSih+GEC4pEbz+NOfeCpLJEn4gfyV1S9S08sG62ls8NPFociA9aWmE1oXfcqwvOkkYhxOw== aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
ssh_pwauth: false #ssh Password authentication disabled
disable_root: false  #The root user is not disabled 
package_update: true #system will still upadet packages
packages:
  - curl  #gets url
  - wget #dowloads
  - mariadb-server


runcmd:
  - sudo apt update
  - sudo apt -y install mariadb-server php-mysqli
  - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;"
  - sudo systemctl restart mariadb.service
  - sudo a2enconf adminer
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - sudo systemctl restart mysql